name: Build

on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker compose -f docker-compose-build.yml build
          docker compose -f docker-compose-build.yml push

      - name: Send POST request
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "success", "message": "Image successfully built and pushed"}' \
            https://portainer.glotesta.com/api/webhooks/78fbfab3-8c5d-409b-9b71-83e269fcb244      
